### ISSUE TITLE
Running YAMP.exe from the release archive yields "Audio Library Not Found!"

### ISSUE THREAD

**Issue by ghost** [azure-hu/YAMP#1]
As the title says, running the main executable results in an error message suggesting that bass.dll can't be found. The library appears to be in the expected location so I'm not sure what the real problem is.

Debugging the YAMP configuration in Visual Studio raises the same error.

OS is Windows Server 2016.

**Comment by azure-hu** [comment]
It is a very old version of my program, and has issues with loading 32 or 64 bit bass.dll. Please try updating Bass.NET, and other bass libraries. When I'm cleaned up my current local repo, I will upload all changes here, or to a new repo.

**Comment by ghost** [comment]
Yep seems to be start OK if you create a x86 platform configuration and run that.
